version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r web_app.zip ./app/* ./doc/* ./admin/*; cd login; zip -r ../web_app.zip ./*; cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web_app.zip
